import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
// https://docusaurus.io/docs/sidebar/autogenerated

const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  allDocSidebar: {
    'Cat A': [{type: 'autogenerated', dirName: '.'},'products/metering-gateways/index'],
    'Cat B': [{type: 'autogenerated', dirName: '.'}]
  },

  productsSidebar: [
    {
      type: 'category',
      label: 'Products',
      items: [
        {type: 'autogenerated', dirName: 'products'},
      ],
    },
  ],

  softwareSidebar: [
    {
      type: 'category',
      label: 'Software',
      items: [
        {type: 'autogenerated', dirName: 'software'},
      ],
    },
  ],

  hardwareSidebar: [
    {
      type: 'category',
      label: 'Hardware',
      items: [
        {type: 'autogenerated', dirName: 'hardware'},
      ],
    },
  ],

  cloudSidebar: [
    {
      type: 'category',
      label: 'Lobaro Cloud',
      items: [
        {type: 'autogenerated', dirName: 'cloud'},
      ],
    },
  ],

  knowledgeBaseSidebar: [
    {
      type: 'category',
      label: 'Knowledge Base',
      items: [
        {type: 'autogenerated', dirName: 'knowledge-base'},
      ],
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],

 allDocSidebar: {
    'Cat A': [{type: 'autogenerated', dirName: '.'},'products/metering-gateways/index'],
    'Cat B': [{type: 'autogenerated', dirName: '.'}]
  },

   */
};

export default sidebars;
